/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Main entry point for the agent conversation.
         *     Orchestrates the ADK Runner to process user input and return the agent's response.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat History
         * @description Retrieve conversation history for a specific session.
         */
        get: operations["get_chat_history_chat__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itinerary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Itineraries
         * @description List recent itineraries for a specific identity.
         */
        get: operations["list_itineraries_itinerary__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itinerary/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Itinerary
         * @description Retrieve the structured itinerary JSON for a dashboard.
         */
        get: operations["get_itinerary_itinerary__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Itinerary Route
         * @description Delete a specific itinerary and its associated agent chat history.
         */
        delete: operations["delete_itinerary_route_itinerary__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Itinerary
         * @description Apply manual updates to an itinerary and re-validate.
         */
        patch: operations["update_itinerary_itinerary__session_id__patch"];
        trace?: never;
    };
    "/profile/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Profile
         * @description Retrieve the global user profile and preferences.
         */
        get: operations["get_user_profile_profile__user_id__get"];
        put?: never;
        /**
         * Update User Profile
         * @description Persist or update user preferences and constraints.
         */
        post: operations["update_user_profile_profile__user_id__post"];
        /**
         * Delete User Profile
         * @description Delete a user's global profile and preferences.
         */
        delete: operations["delete_user_profile_profile__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/destinations/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Popular Destinations
         * @description Fetch a random set of destinations from the database.
         */
        get: operations["get_popular_destinations_destinations_popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/destinations/by-vibe/{vibe}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Destinations By Vibe
         * @description Fetch destinations that match a specific vibe/tag.
         */
        get: operations["get_destinations_by_vibe_destinations_by_vibe__vibe__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/destinations/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Destination
         * @description Fetch a specific destination by name.
         */
        get: operations["get_destination_destinations__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Active health check endpoint.
         *     Verifies MongoDB connectivity and the presence of the Agent Application.
         *     Returns 503 if critical services are unreachable.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatRequest */
        ChatRequest: {
            /**
             * Message
             * @description The user's chat input.
             */
            message: string;
            /**
             * User Id
             * @description The user's ID, optional for anonymous sessions.
             */
            user_id?: string | null;
            /** Session Id */
            session_id: string;
            /**
             * Traveler Profile
             * @description The user's traveler profile constraints and preferences.
             */
            traveler_profile?: {
                [key: string]: unknown;
            } | null;
            /**
             * Itinerary
             * @description The current itinerary state from the UI.
             */
            itinerary?: {
                [key: string]: unknown;
            } | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /**
             * Response
             * @description The agent's text response.
             */
            response: string;
            /**
             * Is Conflict
             * @description True if the current itinerary has validation errors.
             * @default false
             */
            is_conflict: boolean;
            /** @description The latest itinerary state from the agent. */
            itinerary?: components["schemas"]["Itinerary"] | null;
            /** @description The latest traveler profile state from the agent. */
            traveler_profile?: components["schemas"]["TravelerProfile"] | null;
        };
        /** Event */
        Event: {
            /**
             * Day
             * @description The sequential day of the trip (1-indexed).
             */
            day: number;
            /**
             * Segment
             * @description The logistical segment type.
             * @enum {string}
             */
            segment: "TRANSPORT" | "DINING" | "EXPERIENCE" | "LODGING" | "LOGISTICS" | "FLIGHT";
            schedule: components["schemas"]["Schedule"];
            /** @description Optional root-level coordinates for transit origins/destinations. */
            geo?: components["schemas"]["GeoCoordinates"] | null;
            details: components["schemas"]["EventDetails"];
        } & {
            [key: string]: unknown;
        };
        /** EventDetails */
        EventDetails: {
            /**
             * Name
             * @description Display name of the venue or activity.
             */
            name: string;
            /**
             * Description
             * @description Description of the venue or event.
             */
            description?: string | null;
            /**
             * Notes
             * @description Additional notes or context for the event.
             */
            notes?: string | null;
            /**
             * Image Url
             * @description Image URL for the venue.
             */
            image_url?: string | null;
            /**
             * Category
             * @description Broad category (e.g., Museum, Fine Dining).
             */
            category?: string | null;
            /**
             * City
             * @description Primary city.
             */
            city?: string | null;
            /**
             * Travel Zone
             * @description Micro-location zone within a city.
             */
            travel_zone?: string | null;
            /** @description Geographic coordinates of the venue or location. */
            geo?: components["schemas"]["GeoCoordinates"] | null;
            price?: components["schemas"]["Price"] | null;
            /**
             * Rating
             * @description User rating (1.0 to 5.0).
             */
            rating?: number | null;
            /**
             * User Rating Count
             * @description Number of user reviews.
             */
            user_rating_count?: number | null;
            /**
             * Is Rental
             * @description True if this is a rental car segment.
             * @default false
             */
            is_rental: boolean;
            /**
             * Vehicle Count
             * @description Number of vehicles for large groups.
             * @default 1
             */
            vehicle_count: number;
        } & {
            [key: string]: unknown;
        };
        /** GeoCoordinates */
        GeoCoordinates: {
            /**
             * Latitude
             * @description The latitude coordinate.
             */
            latitude: number;
            /**
             * Longitude
             * @description The longitude coordinate.
             */
            longitude: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Itinerary */
        Itinerary: {
            /**
             * User Id
             * @default
             */
            user_id: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /** Trip Name */
            trip_name: string;
            /** Destination */
            destination?: string | null;
            /**
             * Lodging
             * @description The selected lodging for the trip.
             */
            lodging?: {
                [key: string]: unknown;
            } | null;
            /** Duration Days */
            duration_days: number;
            /** Party Size Total */
            party_size_total: number;
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "final";
            /** Events */
            events: components["schemas"]["Event"][];
            budget?: components["schemas"]["TripBudget"] | null;
            /** Updated At */
            updated_at?: string;
            /**
             * Is Conflict
             * @description True if the itinerary has validation errors.
             * @default false
             */
            is_conflict: boolean;
            /**
             * Validation Errors
             * @description List of human-readable rule violations.
             */
            validation_errors?: string[];
            traveler_profile?: components["schemas"]["TravelerProfile"] | null;
        } & {
            [key: string]: unknown;
        };
        /** ItineraryPatchRequest */
        ItineraryPatchRequest: {
            /**
             * Events
             * @description Updated events from the UI.
             */
            events?: components["schemas"]["Event"][] | null;
            /** @description Updated budget from the UI. */
            budget?: components["schemas"]["TripBudget"] | null;
            /**
             * Destination
             * @description Manual override for the primary destination.
             */
            destination?: string | null;
            /**
             * Lodging
             * @description Manual override for the lodging.
             */
            lodging?: {
                [key: string]: unknown;
            } | null;
            /**
             * Trip Name
             * @description Manual override for the trip name.
             */
            trip_name?: string | null;
            /**
             * Status
             * @description Manual override for the trip status.
             */
            status?: ("draft" | "final") | null;
            /** @description Updated traveler profile. */
            traveler_profile?: components["schemas"]["TravelerProfile"] | null;
        };
        /** Price */
        Price: {
            /**
             * Amount
             * @description The numeric cost of the segment.
             */
            amount: number;
            /**
             * Currency
             * @description 3-letter ISO currency code.
             * @default USD
             */
            currency: string;
            /**
             * Is Estimated
             * @description Whether the price is a placeholder or confirmed.
             * @default true
             */
            is_estimated: boolean;
        };
        /** ProfileUpdateRequest */
        ProfileUpdateRequest: {
            /** Party Size */
            party_size?: number | null;
            budget?: components["schemas"]["TripBudget"] | null;
            preferences?: components["schemas"]["UserProfilePreferences"] | null;
            /** Room Sharing */
            room_sharing?: boolean | null;
            /** People Per Room */
            people_per_room?: number | null;
            /** Interests */
            interests?: string[] | null;
            /**
             * Starting Location
             * @description Catch-all for UI sending location at the root level
             */
            starting_location?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Schedule */
        Schedule: {
            /**
             * Local Start Time
             * @description ISO 8601 datetime string for local start time (must include date and time).
             */
            local_start_time: string;
            /**
             * Local End Time
             * @description ISO 8601 datetime string for local end time.
             */
            local_end_time?: string | null;
            /**
             * Start Time Utc
             * @description UTC normalized start time.
             */
            start_time_utc?: string | null;
            /**
             * End Time Utc
             * @description UTC normalized end time.
             */
            end_time_utc?: string | null;
            /**
             * Timezone
             * @description IANA Timezone ID (e.g., 'America/Los_Angeles'). You MUST explicitly provide the correct timezone.
             * @default America/New_York
             */
            timezone: string;
            /**
             * Applied Buffer Minutes
             * @description Buffer calculated by validation logic.
             */
            applied_buffer_minutes?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** TravelerProfile */
        TravelerProfile: {
            /**
             * Party Size
             * @default 1
             */
            party_size: number;
            budget?: components["schemas"]["TripBudget"] | null;
            preferences?: components["schemas"]["UserProfilePreferences"];
            /**
             * Room Sharing
             * @default false
             */
            room_sharing: boolean;
            /**
             * People Per Room
             * @default 2
             */
            people_per_room: number;
            /** Interests */
            interests?: string[];
        };
        /** TripBudget */
        TripBudget: {
            /**
             * Total Limit
             * @default 0
             */
            total_limit: number;
            /**
             * Currency
             * @default USD
             */
            currency: string;
        };
        /** UserProfilePreferences */
        UserProfilePreferences: {
            /**
             * Risk Tolerance
             * @default relaxed
             * @enum {string}
             */
            risk_tolerance: "relaxed" | "strict";
            /**
             * Circadian Preference
             * @default night_owl
             * @enum {string}
             */
            circadian_preference: "early_bird" | "night_owl";
            /**
             * Activity Density
             * @default medium
             * @enum {string}
             */
            activity_density: "low" | "medium" | "high";
            /**
             * Group Planning Per Person
             * @default false
             */
            group_planning_per_person: boolean;
            /**
             * Transport Preference
             * @default public
             * @enum {string}
             */
            transport_preference: "public" | "rideshare" | "rental";
            /**
             * Personal Transport Available
             * @default false
             */
            personal_transport_available: boolean;
            /**
             * Starting Location
             * @description The origin location for the trip.
             */
            starting_location?: string | null;
            /**
             * Start Date
             * @description Start date in YYYY-MM-DD
             */
            start_date?: string | null;
            /**
             * End Date
             * @description End date in YYYY-MM-DD
             */
            end_date?: string | null;
            /**
             * Target Duration Days
             * @description Target trip duration
             */
            target_duration_days?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_history_chat__session_id__get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_itineraries_itinerary__get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_itinerary_itinerary__session_id__get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_itinerary_route_itinerary__session_id__delete: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_itinerary_itinerary__session_id__patch: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Itinerary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_profile__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TravelerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_profile_profile__user_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TravelerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_profile_profile__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_popular_destinations_destinations_popular_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_destinations_by_vibe_destinations_by_vibe__vibe__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                vibe: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_destination_destinations__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
