apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: travel-aigent-api
spec:
  template:
    metadata:
      annotations:
        build-id: "BUILD_ID_PLACEHOLDER"
    spec:
      # Placeholders to be replaced by sed in cloudbuild.yaml
      serviceAccountName: travel-aigent-runner@PROJECT_ID_PLACEHOLDER.iam.gserviceaccount.com
      containers:
        - image: us-central1-docker.pkg.dev/PROJECT_ID_PLACEHOLDER/travel-aigent/api:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: "PROJECT_ID_PLACEHOLDER"
            - name: GOOGLE_CLOUD_LOCATION
              value: "us-central1"
            - name: VOYAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: VOYAGE_API_KEY
                  key: latest
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GOOGLE_MAPS_API_KEY
                  key: latest
            - name: FRONTEND_URL
              value: "FRONTEND_URL_PLACEHOLDER"
            # We map the secret directly to the env var for the code to consume
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: MONGODB_URI
                  key: latest
