[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my_travel_aigent"
version = "0.1.0"
description = "Autonomous travel assistant powered by Gemini and ADK"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "motor>=3.3.0",
    "pydantic>=2.0.0",
    "python-dotenv",
    "google-adk>=1.33.0",
    "pymongo",
    "googlemaps",
    "google-genai",
    "voyageai",
    "google-maps-places",
    "PyYAML",
    "google-cloud-storage",
    "shapely",
    "google-cloud-secret-manager"
]

[project.optional-dependencies]
dev = []

[tool.setuptools.packages.find]
include = ["gemini_agent*"]